version: '3.8'
services:
   db:
     image: mysql:5.7
     container_name: tickmaster_db
     restart: unless-stopped
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: tickmaster
       MYSQL_USER: db_user
       MYSQL_PASSWORD: db_password
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql

volumes:
   db_data: